apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mundoactivate-dev
  namespace: argocd
spec:
  project: mundoactivate
  source:
    repoURL: https://github.com/ingmarbol/mundoactivate-platform.git
    targetRevision: main
    path: gitops/apps/mundoactivate/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: mundoactivate-dev
  syncPolicy:
    automated:
      enabled: true
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true

